apiVersion: v1
kind: Service
metadata:
  name: officespace-service
spec:
  type: LoadBalancer
  selector:
    app: officespace
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
