version: "3.8"

services:
  db:
    image: postgres:15
    container_name: officespace_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: officespace
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  server:
    build: .
    container_name: officespace_server
    ports:
      - "3000:3000"
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: 12345
      DB_NAME: officespace
    depends_on:
      - db
    restart: unless-stopped

volumes:
  postgres_data:
