apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: officespace-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: officespace-server
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70
